name: Recipe Graphql CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      PORT: 3000
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set the correct Node version using nvm
      shell: bash -l {0}
      run: nvm install
    - name: Run npm install
      run: npm i
    - name: Run tests
      run: npm test
